---
- hosts: servers
  sudo: yes
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
    - name: Installs git
      apt: pkg=git state=installed update_cache=true

  handlers:
    - name: start nginx
      service: name=nginx state=started